sudo: required
services:
  - docker

before_install:
  - docker build -t semrahkn/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true semrahkn/react-test npm test

after_success:
  - docker build -t semrahkn/multi-client ./client
  - docker build -t semrahkn/multi-nginx ./nginx
  - docker build -t semrahkn/multi-server ./server
  - docker build -t semrahkn/multi-worker ./worker
  #Login to docker cli, $ variables are taken from env variables of travis
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push semrahkn/multi-client
  - docker push semrahkn/multi-nginx
  - docker push semrahkn/multi-server
  - docker push semrahkn/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-923445559289'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY